app:
  mode: debug
  log:
    path: logs/haolinju.log
    max_age: 168
    rotation_time: 249
server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1
  grpc:
    addr: 0.0.0.0:9001
    timeout: 1
# 数据库
db:
  mysql:
    haolinju:
      dsn: root:liushuaicai@tcp(127.0.0.1:3306)/plan?timeout=1s&readTimeout=1s&writeTimeout=1s&parseTime=true&loc=Local&charset=utf8mb4,utf8
      max: 500
      idle: 20
      life_time: 600
      log_mode: true
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2
    write_timeout: 0.2